# Generated by Django 5.0.6 on 2024-06-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_star',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
